- name: Deploy to Cloudflare Workers with Wrangler2
  # You may pin to the exact commit or the version.
  # uses: RhinoCodes/wrangler2-action@970324c77472e1259c61ecd8b08ce894f0848ce2
  uses: RhinoCodes/wrangler2-action@1.4.0
  with:
    # (Legacy) Your Cloudflare API Key
    apiKey: # optional
    # Your Cloudflare API Token
    apiToken: # optional
    # (Legacy) Your Cloudflare Email
    email: # optional
    # The environment you'd like to publish your Workers project to - must be defined in wrangler.toml
    environment: # optional
    # The relative path which Wrangler commands should be run from
    workingDirectory: # optional
    # The version of Wrangler you'd like to use to publish your Workers project
    wranglerVersion: # optional
    # A new line deliminated string of environment variable names that should be configured as Worker secrets
    secrets: # optional
    # Commands to execute before publishing the Workers project
    preCommands: # optional
    # Commands to execute after publishing the Workers project
    postCommands: # optional
    # Set to false to skip publishing your Worker project and secrets.  Defaults to true.
    publish: # optional
